// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8c_-0m3ZFjy9dqTl5aj1vUTPzjkmf5E4',
    appId: '1:64192831640:web:f1ea0f3aae8aa2dcee30ed',
    messagingSenderId: '64192831640',
    projectId: 'todo-cabe8',
    authDomain: 'todo-cabe8.firebaseapp.com',
    storageBucket: 'todo-cabe8.appspot.com',
    measurementId: 'G-H248LG4CL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQyPDMpF6s-nTIgmYOpeKBazdrVE4P_c',
    appId: '1:64192831640:android:b8bc921079ec56abee30ed',
    messagingSenderId: '64192831640',
    projectId: 'todo-cabe8',
    storageBucket: 'todo-cabe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMqU5yAWRk2oBnS1hh1BV7upnLHvcj8tE',
    appId: '1:64192831640:ios:c4dc1a296942f628ee30ed',
    messagingSenderId: '64192831640',
    projectId: 'todo-cabe8',
    storageBucket: 'todo-cabe8.appspot.com',
    iosBundleId: 'com.example.toDoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMqU5yAWRk2oBnS1hh1BV7upnLHvcj8tE',
    appId: '1:64192831640:ios:3f9f5276e7997d21ee30ed',
    messagingSenderId: '64192831640',
    projectId: 'todo-cabe8',
    storageBucket: 'todo-cabe8.appspot.com',
    iosBundleId: 'com.example.toDoFinal.RunnerTests',
  );
}
